version: "3.8"

services:
  iris:
    # 現在のディレクトリ（. で示される）にある Dockerfile を使用してイメージをビルドする
    build: .
    container_name: iris_docker
    ports:
      - "52773:52773"
    volumes:
      - iris-data:/usr/irissys
    environment:
      #　ISC_DATA_DIRECTORY は、InterSystems IRIS で使用される環境変数の一つ
      - ISC_DATA_DIRECTORY=/usr/irissys

volumes:
  iris-data:
