version: "3.8"

services:
  iris:
    # 現在のディレクトリ（. で示される）にある Dockerfile を使用してイメージをビルドする
    build: .
    container_name: iris_docker
    ports:
      - "52773:52773"
    # Docker管理ボリュームに対してデータを保存。/path/to/local/directory:/usr/irissysとして"/"をつけてローカルディレクトリを指定するとローカルPCの見える場所にデータを保存可能。
    volumes:
      - iris-data:/usr/irissys
    restart: always
    environment:
      #　ISC_DATA_DIRECTORY は、InterSystems IRIS で使用される環境変数の一つ
      - ISC_DATA_DIRECTORY=/usr/irissys
      - TZ=JST-9

volumes:
  iris-data:
